#!/bin/bash
# 
# I'm using this script to monitor the size of
# the minified source of chorus.core plus the
# twitter module, which I consider to be a core 
# metric

cake compress > /dev/null
TOTAL=$(mktemp)
cat dist/chorus.twitter.min.js dist/timeago.min.js > $TOTAL
wc -c $TOTAL
gzip -c $TOTAL | wc -c
