#!/bin/bash
# 
# I'm using this script to monitor the size of
# the minified source of chorus.core plus the
# twitter module, which I consider to be a core 
# metric

cake compress > /dev/null
TOTAL=$(mktemp)
cat dist/chorus.twitter.min.js demo/jquery.timeago.js | uglifyjs > $TOTAL
minified=$(wc -c < $TOTAL) 
zipped=$(gzip -c < $TOTAL | wc -c)
echo "minified: ${minified} bytes"
echo "zipped:   ${zipped} bytes"

